pool:
  name: Hosted Windows 2019 with VS2019

variables:
- group: iot-module-pump-group

steps:
- task: Docker@0
  displayName: 'Build Grafana'
  inputs:
    azureSubscription: '$(SERVICE_ENDPOINT)'
    azureContainerRegistry: '$(ACR_REGISTRY)'
    dockerFile: grafana/Dockerfile
    imageName: 'grafana:windows-$(Build.BuildId)'

- task: Docker@0
  displayName: 'Build InfluxDB'
  inputs:
    azureSubscription: '$(SERVICE_ENDPOINT)'
    azureContainerRegistry: '$(ACR_REGISTRY)'
    dockerFile: influxdb/Dockerfile
    imageName: 'influxdb:windows-$(Build.BuildId)'

- task: Docker@0
  displayName: 'Push Grafana'
  inputs:
    azureSubscription: '$(SERVICE_ENDPOINT)'
    azureContainerRegistry: '$(ACR_REGISTRY)'
    action: 'Push an image'
    imageName: 'grafana:windows-$(Build.BuildId)'

- task: Docker@0
  displayName: 'Push InfluxDB'
  inputs:
    azureSubscription: '$(SERVICE_ENDPOINT)'
    azureContainerRegistry: '$(ACR_REGISTRY)'
    action: 'Push an image'
    imageName: 'influxdb:windows-$(Build.BuildId)'
