# Required Variables
# ACR_HOST:  myregistry.azurecr.io
# ACR_USER:  registryUser
# ACR_PASSWORD: registryPassword
# ACR_REGISTRY: {"loginServer":"{REGISTRY_NAME}.azurecr.io", "id" : "/subscriptions/{azureSubscription}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.ContainerRegistry/registries/{registryName"}
# SERVICE_ENDPOINT: myService


pool:
  name: Azure Pipelines


steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"