# Required Variables
# ACR_HOST:  myregistry.azurecr.io
# ACR_USER:  registryUser
# ACR_PASSWORD: registryPassword
# ACR_REGISTRY: {"loginServer":"{REGISTRY_NAME}.azurecr.io", "id" : "/subscriptions/{azureSubscription}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.ContainerRegistry/registries/{registryName"}
# SERVICE_ENDPOINT: myService


pool:
  name: Azure Pipelines

variables:
- group: iot-module-pump-group

steps:
- task: Docker@0
  displayName: 'Build Grafana'
  inputs:
    azureSubscription: '$(SERVICE_ENDPOINT)'
    azureContainerRegistry: '$(ACR_REGISTRY)'
    dockerFile: grafana/Dockerfile
    imageName: 'grafana:windows-$(Build.BuildId)'
