# Required Variables
# ACR_HOST:  myregistry.azurecr.io
# ACR_USER:  registryUser
# ACR_PASSWORD: registryPassword
# ACR_REGISTRY: {"loginServer":"{REGISTRY_NAME}.azurecr.io", "id" : "/subscriptions/{azureSubscription}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.ContainerRegistry/registries/{registryName"}
# SERVICE_ENDPOINT: myService
# 



pool:
  name: Azure Pipelines
steps:
- task: Docker@0
  displayName: 'Build Grafana'
  inputs:
    azureSubscription: $(SERVICE_ENDPOINT)
    azureContainerRegistry: $(ACR_REGISTRY)
    dockerFile: grafana/Dockerfile
    imageName: 'grafana:windows-$(Build.BuildId)'

- task: Docker@0
  displayName: 'Build InfluxDB'
  inputs:
    azureSubscription: $(SERVICE_ENDPOINT)
    azureContainerRegistry: $(ACR_REGISTRY)
    dockerFile: influxdb/Dockerfile
    imageName: 'grafana:windows-$(Build.BuildId)'

- task: Docker@0
  displayName: 'Push Grafana'
  inputs:
    azureSubscription: $(SERVICE_ENDPOINT)
    azureContainerRegistry: $(ACR_REGISTRY)
    action: 'Push an image'
    imageName: 'grafana:windows-:$(Build.BuildId)'

- task: Docker@0
  displayName: 'Push InfluxDB'
  inputs:
    azureSubscription: $(SERVICE_ENDPOINT)
    azureContainerRegistry: $(ACR_REGISTRY)
    action: 'Push an image'
    imageName: 'influxdb:windows-:$(Build.BuildId)'
