version: "3"
services:

  influxdb:
    build: influxdb
    image: danielscholl/influxdb:windows-1.0.0
    container_name: influxdb
    hostname: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring

  grafana:
    build: grafana
    image: danielscholl/grafana:windows-1.0.0
    container_name: grafana
    depends_on:
      - influxdb
    restart: always
    ports:
      - 8080:8080
    networks:
      - monitoring

networks:
  monitoring:

    
