# config file version
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: metricsdatabase
    url: http://influxdb:8086
    jsonData:
      timeInterval: "10s"
    isDefault: true
